package main

import (
	"encoding/json"
	"net/http"

	"github.com/craigbucher/learn-http-servers/internal/auth"
	"github.com/craigbucher/learn-http-servers/internal/database"
)

func (cfg *apiConfig) handlerUsersUpdate(w http.ResponseWriter, r *http.Request) {
	// create a struct with two fields: password and email:
	type parameters struct {
		Password string `json:"password"`
		Email    string `json:"email"`
	}

	// create a struct that embeds User:
	// Embedding “promotes” User’s fields/methods to response, so you can access them directly 
	// on a response value
	// (It lets you return a User-like response while optionally adding more fields later without
	// rewriting access patterns)
	type response struct {
		User
	}

	// read the Authorization header, expecting "Bearer <token>", and return the token string:
	token, err := auth.GetBearerToken(r.Header)
	if err != nil {
		// If the access token is malformed or missing, respond with a 401 status code:
		respondWithError(w, http.StatusUnauthorized, "Couldn't find JWT", err)
		return
	}
	// validate the JWT and extract the authenticated user’s ID:
	userID, err := auth.ValidateJWT(token, cfg.jwtSecret)
	if err != nil {
		// If the access token is malformed or missing, respond with a 401 status code:
		respondWithError(w, http.StatusUnauthorized, "Couldn't validate JWT", err)
		return
	}

	// reads and parses the JSON request body into a Go struct:
	// create a decoder over the HTTP body:
	decoder := json.NewDecoder(r.Body)
	// prepares the target struct:
	params := parameters{}
	// fill params from the JSON:
	err = decoder.Decode(&params)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't decode parameters", err)
		return
	}

	// hash the provided plaintext password before storing it:
	hashedPassword, err := auth.HashPassword(params.Password)
	if err != nil {
		// If hashing fails, it returns 500 and stops to avoid saving an unhashed or invalid password:
		respondWithError(w, http.StatusInternalServerError, "Couldn't hash password", err)
		return
	}

	//  update the authenticated user in the database and return the updated record:
	// (database.UpdateUserParams is a struct generated by sqlc for the UpdateUser query)
	user, err := cfg.db.UpdateUser(r.Context(), database.UpdateUserParams{
		ID:             userID,
		Email:          params.Email,
		HashedPassword: hashedPassword,
	})
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't update user", err)
		return
	}

	// build and send a 200 OK JSON response with a sanitized user object:
	// (It copies only safe fields from the DB result (ID, CreatedAt, UpdatedAt, Email), omitting 
	// sensitive data like hashed passwords)
	respondWithJSON(w, http.StatusOK, response{
		User: User{
			ID:        user.ID,
			CreatedAt: user.CreatedAt,
			UpdatedAt: user.UpdatedAt,
			Email:     user.Email,
			IsChirpyRed: user.IsChirpyRed,
		},
	})
}
